# Overview of the data product

The data product of spatial signatures in Great Britain contains the data illustrated by this notebook.

In [1]:
cd ../../urbangrammar_samba/spatial_signatures/data_product/

/home/jovyan/work/urbangrammar_samba/spatial_signatures/data_product

In [2]:
import pandas
import geopandas

## Geometry

Signature geometry with signature type and polygon ID.

In [3]:
geopandas.read_file("spatial_signatures_GB.gpkg", rows=10)

/opt/conda/lib/python3.8/site-packages/geopandas/geodataframe.py:577: RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.
  for feature in features_lst:

,id,code,type,geometry
0,0_COA,COA,Countryside agriculture,"POLYGON ((62220.000 798500.000, 62110.000 7985..."
1,1_COA,COA,Countryside agriculture,"POLYGON ((63507.682 796515.169, 63471.097 7965..."
2,2_COA,COA,Countryside agriculture,"POLYGON ((65953.174 802246.172, 65950.620 8022..."
3,3_COA,COA,Countryside agriculture,"POLYGON ((67297.740 803435.800, 67220.289 8034..."
4,4_COA,COA,Countryside agriculture,"POLYGON ((75760.000 852670.000, 75700.000 8527..."
5,5_COA,COA,Countryside agriculture,"POLYGON ((78663.640 819587.579, 78665.420 8195..."
6,6_COA,COA,Countryside agriculture,"POLYGON ((79020.596 820041.322, 79022.514 8200..."
7,7_COA,COA,Countryside agriculture,"POLYGON ((79088.951 819900.971, 79089.062 8199..."
8,8_COA,COA,Countryside agriculture,"POLYGON ((79843.335 818918.964, 79843.296 8189..."
9,9_COA,COA,Countryside agriculture,"POLYGON ((88080.000 14970.000, 88078.269 14961..."

## Geometry description

Summary of input characters per each geometry.

In [4]:
pandas.read_csv("per_geometry.csv")

,id,form_sdbAre,form_sdbPer,form_sdbCoA,form_ssbCCo,form_ssbCor,form_ssbSqu,form_ssbERI,form_ssbElo,form_ssbCCM,...,func_supermarkets_nearest,func_supermarkets_counts,func_listed_nearest,func_listed_counts,func_fhrs_nearest,func_fhrs_counts,func_culture_nearest,func_culture_counts,func_water_nearest,func_retail_centrenearest
0,0_COA,129.933434,45.146514,0.202279,0.540968,4.172237,0.524401,0.993543,0.622563,8.027774,...,1444.935973,0.454774,890.196235,3.572864,341.152792,77.364322,NaN,0.0,136.483329,93403.761607
1,4_COA,258.461742,65.650654,5.278706,0.500917,4.376384,0.558092,0.975591,0.571528,11.094158,...,9034.336389,0.000000,736.182262,1.718412,642.509775,126.115523,NaN,0.0,139.419780,58846.096367
2,9_COA,122.655396,46.888304,0.000000,0.509570,4.336957,0.606492,0.981817,0.578105,8.168939,...,NaN,0.000000,112.232624,4.935484,309.115193,61.000000,NaN,0.0,80.087762,4762.653237
3,11_COA,190.308946,59.022824,0.764543,0.494519,4.541985,0.997673,0.967397,0.598092,10.134862,...,NaN,0.000000,281.289369,8.043478,198.296841,4.326087,NaN,0.0,74.377682,4378.879114
4,14_COA,146.477816,50.308964,0.229756,0.509439,4.382090,0.769455,0.974591,0.607979,8.836870,...,2296.657968,0.023599,519.019717,7.519174,281.737308,24.020649,NaN,0.0,199.544381,1698.769041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96699,94815_LOU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,967.354980,1.000000,733.508972,18.000000,294.217987,62.000000,4342.378906,0.0,0.000000,731.905179
96700,94853_LOU,542.697500,98.334230,0.000000,0.518628,4.000000,0.078285,0.999855,0.516309,18.248347,...,547.687012,3.000000,97.226997,77.000000,112.362999,1346.000000,1062.750000,1.0,160.527776,213.305247
96701,94892_LOU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,457.170990,5.000000,0.000000,515.000000,38.470001,2364.000000,401.411011,2.0,410.039048,0.000000
96702,96021_LOU,180.378400,57.278130,0.000000,0.499708,4.000000,0.025284,1.000037,0.484826,10.717266,...,327.584015,4.000000,251.115005,3.000000,153.737000,301.000000,2968.321045,0.0,710.912280,317.166726
96703,96702_OUT,54.747100,29.614573,0.000000,0.634613,4.000000,0.048043,1.000000,0.932525,5.238355,...,41921.593750,0.000000,0.000000,4.000000,1227.026001,0.000000,NaN,0.0,0.000000,25185.139279

## Signature type description

Summary of input characters per each signature type.

In [5]:
pandas.read_csv("per_type.csv")

,code,type,form_sdbAre,form_sdbPer,form_sdbCoA,form_ssbCCo,form_ssbCor,form_ssbSqu,form_ssbERI,form_ssbElo,...,func_supermarkets_nearest,func_supermarkets_counts,func_listed_nearest,func_listed_counts,func_fhrs_nearest,func_fhrs_counts,func_culture_nearest,func_culture_counts,func_water_nearest,func_retail_centrenearest
0,ACS,Accessible suburbia,176.949135,53.902697,0.476838,0.534856,4.253845,0.775272,0.987707,0.642271,...,828.822261,1.890519,744.223994,11.273578,218.460768,334.434991,5384.638746,0.059113,542.613661,849.447871
1,CRN,Connected residential neighbourhoods,272.522220,69.119967,1.069872,0.480941,4.445515,1.466426,0.979415,0.555468,...,679.958940,2.855980,596.613654,24.279146,152.479922,692.664050,3946.052517,0.129197,555.964942,536.469155
2,COA,Countryside agriculture,204.100400,56.048984,0.505831,0.506275,4.371156,0.809087,0.977789,0.600065,...,4751.226429,0.089042,557.936276,11.223066,725.690643,44.465529,13156.203765,0.003804,304.488181,4943.972107
3,DRN,Dense residential neighbourhoods,375.598290,80.558473,2.127340,0.472554,4.694714,1.863620,0.969912,0.557054,...,661.765594,3.127412,506.614715,37.474705,144.021617,860.927102,3497.511181,0.259194,483.124139,421.093530
4,DUN,Dense urban neighbourhoods,588.359559,107.362849,5.034084,0.435714,5.208242,3.278419,0.950431,0.519821,...,587.276810,4.436632,350.890339,62.783422,106.084358,1568.443597,2287.432199,0.476118,528.850109,224.326713
5,DIS,Disconnected suburbia,212.713958,61.631662,0.519372,0.491588,4.347900,1.019293,0.981779,0.573786,...,761.858373,2.067315,729.608517,24.181257,217.945624,342.081722,5831.523433,0.077958,523.050240,725.573382
6,DIU,Concentrated urbanity,3713.379427,376.300388,159.087608,0.425186,12.484667,18.589482,0.776950,0.594314,...,229.903096,22.510563,31.732228,685.156338,16.219050,6297.607746,702.750880,10.392254,565.248203,29.803442
7,GRQ,Gridded residential quarters,283.892607,69.667245,0.749026,0.491754,4.506685,1.663151,0.976842,0.584548,...,577.683974,3.409903,516.197376,31.771826,129.244204,1081.376510,4094.915253,0.240503,522.087434,445.518972
8,HDU,Hyper concentrated urbanity,3358.099586,330.818576,90.819544,0.446292,9.273438,22.513954,0.802892,0.617669,...,324.416312,18.791045,69.749236,1142.567164,14.101269,9213.145522,351.325110,34.197761,759.604208,32.544669
9,LOU,Local urbanity,823.354285,135.543919,12.666729,0.409310,6.014239,5.071848,0.919085,0.506415,...,483.017862,6.848327,216.858599,140.031073,82.468961,2167.909991,1273.226897,1.129622,507.706457,161.854989
10,MEU,Metropolitan urbanity,2413.938716,283.935149,118.946949,0.395862,9.717504,12.406894,0.820142,0.527758,...,299.930496,17.271958,51.874364,456.529630,40.063982,4490.949206,644.531259,4.446825,467.713631,66.318054
11,OPS,Open sprawl,226.715098,59.639780,0.900478,0.518531,4.371939,0.985729,0.982452,0.622301,...,948.025914,1.469023,760.257254,18.171441,267.238602,253.875226,6309.753341,0.061560,378.356187,1002.663064
12,REU,Regional urbanity,1480.260902,195.978660,43.190998,0.393035,7.776863,8.844805,0.869514,0.512959,...,331.067781,12.531123,115.004786,324.500752,56.865240,3163.829678,850.254487,2.233070,461.415859,90.874497
13,URB,Urban buffer,209.421858,55.941702,0.743395,0.523632,4.340540,0.859973,0.982904,0.630125,...,1752.873479,0.654018,673.931399,16.138833,379.169823,132.661846,8939.647136,0.024052,345.790747,2102.455609
14,WAL,Warehouse/Park land,393.216097,75.680270,3.263039,0.469466,4.564890,1.352536,0.976102,0.542256,...,1043.835409,1.427596,934.001152,10.570084,256.220805,271.092537,5121.469150,0.058667,417.431851,898.174463
15,WIC,Wild countryside,209.855382,57.122052,0.223542,0.501939,4.381272,0.706130,0.976522,0.589908,...,9854.123937,0.028975,1324.025044,4.212720,1699.169649,33.073293,20695.290665,0.001680,236.730324,11041.324478

## Keys

Key to codes denoting measured characters.

In [6]:
pandas.read_csv("key.csv")

              Unnamed: 0                                                  0
0        func_population                                         Population
1      func_night_lights                                       Night lights
2    func_workplace_abde  Workplace population [Agriculture, energy and ...
3       func_workplace_c               Workplace population [Manufacturing]
4       func_workplace_f                Workplace population [Construction]
..                   ...                                                ...
111          form_lseERI          equivalent rectangular index of enclosure
112          form_lseCWA             compactness-weighted axis of enclosure
113          form_lteOri                           orientation of enclosure
114          form_lteWNB         perimeter-weighted neighbours of enclosure
115          form_lieWCe                    area-weighted ETCs of enclosure

[116 rows x 2 columns]

Key linking signature type and type code.

In [7]:
pandas.read_csv("type_code.csv")

                               type_name type_code
0                Countryside agriculture       COA
1                    Accessible suburbia       ACS
2                            Open sprawl       OPS
3                       Wild countryside       WIC
4                    Warehouse/Park land       WAL
5           Gridded residential quarters       GRQ
6                           Urban buffer       URB
7                  Disconnected suburbia       DIS
8       Dense residential neighbourhoods       DRN
9   Connected residential neighbourhoods       CRN
10            Dense urban neighbourhoods       DUN
11                        Local urbanity       LOU
12                 Concentrated urbanity       DIU
13                     Regional urbanity       REU
14                 Metropolitan urbanity       MEU
15           Hyper concentrated urbanity       HDU
16                               outlier       OUT

## LSOA interpolation

Interpolation of signature types to LSOA geometry.

In [8]:
pandas.read_csv("lsoa_estimates.csv", nrows=10)

,LSOA11CD,primary_code,primary_type,COA,ACS,OPS,WIC,WAL,GRQ,URB,DIS,DRN,CRN,DUN,LOU,DIU,REU,OUT,MEU,HDU
0,E01000007,DUN,Dense urban neighbourhoods,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.822703,0.177297,0.0,0.0,0.0,0.0,0.0
1,E01000015,DRN,Dense residential neighbourhoods,0.0,0.000000,0.001117,0.0,0.000000,0.000000,0.0,0.022815,0.707635,0.136794,0.130251,0.000000,0.0,0.0,0.0,0.0,0.0
2,E01000030,DRN,Dense residential neighbourhoods,0.0,0.000000,0.000000,0.0,0.427742,0.000000,0.0,0.000000,0.572258,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
3,E01000085,DUN,Dense urban neighbourhoods,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.171808,0.126567,0.701626,0.000000,0.0,0.0,0.0,0.0,0.0
4,E01000118,CRN,Connected residential neighbourhoods,0.0,0.339714,0.036230,0.0,0.000000,0.132012,0.0,0.000000,0.004280,0.487764,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
5,E01000125,CRN,Connected residential neighbourhoods,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.867404,0.132596,0.000000,0.0,0.0,0.0,0.0,0.0
6,E01000136,WAL,Warehouse/Park land,0.0,0.000000,0.051477,0.0,0.443033,0.000000,0.0,0.012310,0.427006,0.029230,0.036944,0.000000,0.0,0.0,0.0,0.0,0.0
7,E01000145,CRN,Connected residential neighbourhoods,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
8,E01000146,CRN,Connected residential neighbourhoods,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.083465,0.916535,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
9,E01000166,OPS,Open sprawl,0.0,0.000000,0.893081,0.0,0.091906,0.000000,0.0,0.015013,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0

## OA interpolation
Interpolation of signature types to OA geometry.

In [9]:
pandas.read_csv("output_area_estimates.csv", nrows=10)

,OA11CD,primary_code,primary_type,COA,ACS,OPS,WIC,WAL,GRQ,URB,DIS,DRN,CRN,DUN,LOU,DIU,REU,OUT,MEU,HDU
0,E00000001,DIU,Concentrated urbanity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,E00000003,DIU,Concentrated urbanity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,E00000005,DIU,Concentrated urbanity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,E00000007,DIU,Concentrated urbanity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,E00000010,DIU,Concentrated urbanity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
5,E00000012,DIU,Concentrated urbanity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6,E00000013,DIU,Concentrated urbanity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7,E00000014,DIU,Concentrated urbanity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8,E00000016,DIU,Concentrated urbanity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9,E00000017,DIU,Concentrated urbanity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0